export const dataPortfolio = [
  {
    title: 'TodoDo',
    description:
      'TodoDo graphical interface and CRUD management, supported by the API created by @Matias where the user login and TodoDo management are generated.',
    img: 'https://user-images.githubusercontent.com/26255765/203454494-a5eb829a-4214-4ef7-aab0-1af754046bec.png',
    url: 'https://dancing-jelly-4ba1f3.netlify.app/',
    status: 'building',
    tags: ['react', 'tailwind', 'javascript'],
  },
  {
    title: 'Time counter for christmas',
    description:
      'Christmas counter for the Caicedo brand, where Date was instantiated to format the deadline date for Christmas, time was managed with the use of states.',
    img: 'https://user-images.githubusercontent.com/26255765/201201489-de7bca67-6a54-46a0-9331-129ce610ac9f.png',
    url: 'https://caicedodev.github.io/Christmas/',
    status: 'completed',
    tags: ['react', 'tailwind', 'javascript'],
  },
  {
    title: 'Landing Travel Cai',
    description:
      'Landing page search for travel sites, where night mode was implemented, section management for navigation within the page, grid was used for the layout.',
    img: 'https://user-images.githubusercontent.com/26255765/201198687-588b945a-1136-49e7-80ec-9a85a6b319cd.png',
    url: 'https://jose.caicedo.dev/landing-travel-app/',
    status: 'completed',
    tags: ['react', 'tailwind', 'javascript'],
  },
  {
    title: 'Movie app',
    description:
      'Application generated with the openBootcamp community, in the open-week-apps program where the Fulltasck team allowed practicing the use of agile methodology for the creation of the project in less than a week.',
    img: 'https://raw.githubusercontent.com/Open-Bootcamp/movie-app/main/public/preview.png',
    url: 'https://movie-app-eta-six.vercel.app/',
    status: 'completed',
    tags: ['react', 'typescript', 'scss', 'community'],
  },
  {
    title: 'Testimonials cards with react',
    description:
      'Implementation of lazy loading in the testimonial API consumption, supported by axios, using a get method, the design started from the mobile first premise.',
    img: 'https://user-images.githubusercontent.com/26255765/190047975-4d6457b9-f8e0-4d32-aba2-b22d6a855e7e.png',
    url: 'https://jose.caicedo.dev/cardReact/',
    status: 'completed',
    tags: ['react', 'tailwind', 'javascript'],
  },
  {
    title: 'Card Qr componente',
    description:
      'Construction of the QR code component, following the guidelines generated by frontendmentor.io, as a practice resource to refine layout concepts.',
    img: 'https://user-images.githubusercontent.com/26255765/201201022-b8d62a7d-c478-47fc-9c6e-03ff6a2190b4.png',
    url: 'https://jose.caicedo.dev/qr_code_component/',
    status: 'completed',
    tags: ['react', 'javascript', 'css'],
  },
  {
    title: 'Product view card',
    description:
      'Construction of the product view card component, following the guidelines generated by frontendmentor.io, as a practice resource to refine layout concepts.',
    img: 'https://user-images.githubusercontent.com/26255765/191108067-9177cd74-fa9c-451e-933e-5314389dc292.jpg',
    url: 'https://jose.caicedo.dev/product_preview_card/',
    status: 'completed',
    tags: ['react', 'tailwind', 'javascript'],
  },
  {
    title: 'Card profile component',
    description:
      'Construction of the card profile component, following the guidelines generated by frontendmentor.io, as a practice resource to refine layout concepts.',
    img: 'https://user-images.githubusercontent.com/26255765/201203752-88439d93-c2ae-48aa-9502-8e961efada2b.png',
    url: 'https://jose.caicedo.dev/profile_card/',
    status: 'completed',
    tags: ['react', 'css', 'javascript'],
  },
  {
    title: 'Todo list',
    description:
      'Management of the localstorage used as an example task list, where it is possible to generate CRUD and persist data in the DOM of the web browser.',
    img: 'https://user-images.githubusercontent.com/26255765/190924956-03ed4d60-6260-4cec-a265-0b67277fbc4e.png',
    url: 'https://jose.caicedo.dev/todo-list/',
    status: 'completed',
    tags: ['react', 'tailwind', 'javascript'],
  },
  {
    title: 'Form validator',
    description:
      'Form validator supported by regex expressions and the test() method in search of a match of the specific input for sending data to the database.',
    img: 'https://user-images.githubusercontent.com/26255765/201205365-20cb97e7-ad19-4315-bd3a-267b281dc6ff.png',
    url: 'https://jose.caicedo.dev/validadorFormulario/',
    status: 'completed',
    tags: ['react', 'javascript', 'css'],
  },
  {
    title: 'Noteworthy technology acquisitions',
    description:
      'Piano simulation with musical notes where supported by the keyboard event allows to resemble a digital keyboard, in the same way with the use setTimeout() it was possible to simulate the intonation of the cockroach.',
    img: 'https://user-images.githubusercontent.com/26255765/201206157-a4ffc116-28af-419a-9ccd-0119808a54e0.png',
    url: 'https://jose.caicedo.dev/pianojs/',
    status: 'completed',
    tags: ['javascript', 'css'],
  },
]
